# Generated by Django 4.2.3 on 2023-07-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealspiration', '0001_create_custom_user_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorited_items',
            field=models.JSONField(null=True),
        ),
    ]
