# Generated by Django 4.2.5 on 2023-11-01 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ingredient', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=100)),
                ('recipe_url', models.CharField(max_length=150)),
                ('gluten_friendly', models.BooleanField(default=True)),
                ('vegan_friendly', models.BooleanField(default=True)),
                ('vegetarian_friendly', models.BooleanField(default=True)),
                ('lactose_friendly', models.BooleanField(default=True)),
                ('keto_friendly', models.BooleanField(default=True)),
                ('nut_friendly', models.BooleanField(default=True)),
                ('shellfish_friendly', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_ingredient', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bytes.recipe')),
            ],
        ),
    ]
