# Generated by Django 4.2.5 on 2023-12-02 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gluten_free', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_lactose_intolerant', models.BooleanField(default=False)),
                ('is_keto', models.BooleanField(default=False)),
                ('nut_allergy', models.BooleanField(default=False)),
                ('shellfish_allergy', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='recipeingredient',
            name='unique_recipe_ingredient',
        ),
        migrations.AlterModelTable(
            name='recipeingredient',
            table=None,
        ),
    ]
