# Generated by Django 4.2.5 on 2023-12-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bytes', '0002_userpreferences_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_recipe_ingredient'),
        ),
        migrations.AlterModelTable(
            name='recipeingredient',
            table='bytes_recipe_ingredients',
        ),
    ]
